2023-10-06 09:16:58,484 - DEBUG - Using selector: EpollSelector
2023-10-06 09:17:04,712 - INFO - [Serveur] fonction prendre_commande utilisée au temps 6.227337837219238
2023-10-06 09:17:05,714 - INFO - [Pic] fonction ajouter utilisée au temps 7.229583263397217
2023-10-06 09:17:05,714 - INFO - [Serveur] fonction prendre_commande utilisée au temps 7.230088710784912
2023-10-06 09:17:05,715 - INFO - [Pic] fonction retirer utilisée au temps 7.230416774749756
2023-10-06 09:17:06,716 - INFO - [Pic] fonction ajouter utilisée au temps 8.23182201385498
2023-10-06 09:17:06,717 - INFO - [Serveur] fonction prendre_commande utilisée au temps 8.232365608215332
2023-10-06 09:17:06,717 - INFO - [Barman] fonction prepare utilisée au temps 8.232999801635742
2023-10-06 09:17:06,718 - INFO - [Bar] fonction ajouter utilisée au temps 8.233421087265015
2023-10-06 09:17:06,718 - INFO - [Pic] fonction retirer utilisée au temps 8.233785629272461
2023-10-06 09:17:07,719 - INFO - [Pic] fonction ajouter utilisée au temps 9.234360933303833
2023-10-06 09:17:07,719 - INFO - [Serveur] fonction prendre_commande utilisée au temps 9.234843492507935
2023-10-06 09:17:07,720 - INFO - [Barman] fonction prepare utilisée au temps 9.235353231430054
2023-10-06 09:17:07,720 - INFO - [Bar] fonction ajouter utilisée au temps 9.23562502861023
2023-10-06 09:17:07,720 - INFO - [Pic] fonction retirer utilisée au temps 9.23587417602539
2023-10-06 09:17:08,717 - INFO - [Bar] fonction retirer utilisée au temps 10.23268175125122
2023-10-06 09:17:08,717 - INFO - [Serveur] fonction servir utilisée au temps 10.233119487762451
2023-10-06 09:17:08,720 - INFO - [Pic] fonction ajouter utilisée au temps 10.2361421585083
2023-10-06 09:17:08,721 - INFO - [Barman] fonction prepare utilisée au temps 10.236857414245605
2023-10-06 09:17:08,722 - INFO - [Bar] fonction ajouter utilisée au temps 10.237352132797241
2023-10-06 09:17:08,722 - INFO - [Pic] fonction retirer utilisée au temps 10.237729787826538
2023-10-06 09:17:09,720 - INFO - [Bar] fonction retirer utilisée au temps 11.235832929611206
2023-10-06 09:17:09,721 - INFO - [Serveur] fonction servir utilisée au temps 11.236383199691772
2023-10-06 09:17:09,724 - INFO - [Barman] fonction prepare utilisée au temps 11.239381074905396
2023-10-06 09:17:09,724 - INFO - [Bar] fonction ajouter utilisée au temps 11.239905595779419
2023-10-06 09:17:10,723 - INFO - [Bar] fonction retirer utilisée au temps 12.238327503204346
2023-10-06 09:17:10,723 - INFO - [Serveur] fonction servir utilisée au temps 12.238934516906738
2023-10-06 09:17:11,725 - INFO - [Bar] fonction retirer utilisée au temps 13.24126410484314
2023-10-06 09:17:11,726 - INFO - [Serveur] fonction servir utilisée au temps 13.241719007492065
2023-10-06 09:17:42,831 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Serveur.servir() done, defined at /home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/bar_asyncio.py:134> exception=SystemExit()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/bar_asyncio.py", line 143, in servir
    c = self.bar.evacuer() #Renvoie une commande qui peut être un None
  File "/usr/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/usr/lib/python3.10/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/bar_asyncio.py", line 157, in servir
    except:
SystemExit
