2023-10-06 09:13:02,464 - DEBUG - Using selector: EpollSelector
2023-10-06 09:13:08,129 - INFO - [Serveur] fonction prendre_commande utilisée au temps 5.665710687637329
2023-10-06 09:13:09,132 - INFO - [Pic] fonction ajouter utilisée au temps 6.668126583099365
2023-10-06 09:13:09,132 - INFO - [Serveur] fonction prendre_commande utilisée au temps 6.668710947036743
2023-10-06 09:13:09,133 - INFO - [Pic] fonction retirer utilisée au temps 6.669246196746826
2023-10-06 09:13:10,133 - INFO - [Pic] fonction ajouter utilisée au temps 7.669970989227295
2023-10-06 09:13:10,134 - INFO - [Serveur] fonction prendre_commande utilisée au temps 7.6701436042785645
2023-10-06 09:13:10,134 - INFO - [Barman] fonction prepare utilisée au temps 7.6702775955200195
2023-10-06 09:13:10,134 - INFO - [Bar] fonction ajouter utilisée au temps 7.670372486114502
2023-10-06 09:13:10,134 - INFO - [Pic] fonction retirer utilisée au temps 7.670477867126465
2023-10-06 09:13:11,136 - INFO - [Pic] fonction ajouter utilisée au temps 8.67213487625122
2023-10-06 09:13:11,136 - INFO - [Serveur] fonction prendre_commande utilisée au temps 8.672668218612671
2023-10-06 09:13:11,137 - INFO - [Barman] fonction prepare utilisée au temps 8.673203229904175
2023-10-06 09:13:11,137 - INFO - [Bar] fonction ajouter utilisée au temps 8.673478841781616
2023-10-06 09:13:11,137 - INFO - [Pic] fonction retirer utilisée au temps 8.673745155334473
2023-10-06 09:13:12,133 - INFO - [Bar] fonction retirer utilisée au temps 9.669545888900757
2023-10-06 09:13:12,133 - INFO - [Serveur] fonction servir utilisée au temps 9.66999888420105
2023-10-06 09:13:12,137 - INFO - [Pic] fonction ajouter utilisée au temps 9.673924207687378
2023-10-06 09:13:12,138 - INFO - [Barman] fonction prepare utilisée au temps 9.674845695495605
2023-10-06 09:13:12,139 - INFO - [Bar] fonction ajouter utilisée au temps 9.675353527069092
2023-10-06 09:13:12,139 - INFO - [Pic] fonction retirer utilisée au temps 9.67573356628418
2023-10-06 09:13:13,136 - INFO - [Bar] fonction retirer utilisée au temps 10.672688007354736
2023-10-06 09:13:13,137 - INFO - [Serveur] fonction servir utilisée au temps 10.673245906829834
2023-10-06 09:13:13,141 - INFO - [Barman] fonction prepare utilisée au temps 10.67719578742981
2023-10-06 09:13:13,141 - INFO - [Bar] fonction ajouter utilisée au temps 10.67763614654541
2023-10-06 09:13:14,139 - INFO - [Bar] fonction retirer utilisée au temps 11.675633668899536
2023-10-06 09:13:14,140 - INFO - [Serveur] fonction servir utilisée au temps 11.676162481307983
2023-10-06 09:13:15,142 - INFO - [Bar] fonction retirer utilisée au temps 12.678234815597534
2023-10-06 09:13:15,142 - INFO - [Serveur] fonction servir utilisée au temps 12.678450345993042
2023-10-06 09:15:56,621 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Serveur.servir() done, defined at /home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/bar_asyncio.py:134> exception=SystemExit()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/bar_asyncio.py", line 140, in servir
    while True:
  File "/usr/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/usr/lib/python3.10/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ibotcazou/Bureau/Master_data_science/Master2_datascience/Informatique_charbonel/probleme_bar_cocktails/V2_asyncio/bar_asyncio.py", line 151, in servir
    await asyncio.sleep(self.pic.ts)
SystemExit
